// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ClientPortal.Data;

#nullable disable

namespace ClientPortal.Migrations
{
    [DbContext(typeof(PortalDBContext))]
    [Migration("20220704140550_scadarequests")]
    partial class scadarequests
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UMFAPortal.Data.Entities.AMRMeter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("CbSize")
                        .HasColumnType("int");

                    b.Property<string>("CommsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CtSizePrim")
                        .HasColumnType("int");

                    b.Property<int>("CtSizeSec")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Digits")
                        .HasColumnType("int");

                    b.Property<int>("MakeModelId")
                        .HasColumnType("int");

                    b.Property<string>("MeterNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MeterSerial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<float>("ProgFact")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("MakeModelId");

                    b.HasIndex("MeterNo")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AMRMeters");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.AMRScadaUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScadaPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScadaUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SgdUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AMRScadaUsers");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("UmfaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.BuildingSupplierUtility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int");

                    b.Property<int>("UtilitySupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("UtilityId");

                    b.HasIndex("UtilitySupplierId");

                    b.ToTable("BuildingSupplierUtilities");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.MeterMakeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilityId");

                    b.ToTable("MetersMakeModels");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedDtm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.ScadaRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AmrMeterId")
                        .HasColumnType("int");

                    b.Property<int>("AmrScadaUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CurrentRunDTM")
                        .HasColumnType("datetime2");

                    b.Property<int>("HeaderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastRunDTM")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmrMeterId");

                    b.HasIndex("AmrScadaUserId");

                    b.HasIndex("HeaderId");

                    b.ToTable("ScadaRequestDetails");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.ScadaRequestHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDTM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentRunDTM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRunDTM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartRunDTM")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ScadaRequestHeaders");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TariffHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AmpEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmpStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DemandEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DemandStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TOUHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("TariffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TariffDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransmissionZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilitySupplierId")
                        .HasColumnType("int");

                    b.Property<string>("VoltageEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoltageStart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TOUHeaderId");

                    b.HasIndex("UtilitySupplierId");

                    b.ToTable("TariffHeaders");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("TOUDaysOfWeekId")
                        .HasColumnType("int");

                    b.Property<int>("TOUHalfHourId")
                        .HasColumnType("int");

                    b.Property<int>("TOURegisterId")
                        .HasColumnType("int");

                    b.Property<int>("TariffHeaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TOUDaysOfWeekId");

                    b.HasIndex("TOUHalfHourId");

                    b.HasIndex("TOURegisterId");

                    b.HasIndex("TariffHeaderId");

                    b.ToTable("TOUAllocations");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUDaysOfWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayNr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TOUDaysOfWeeks");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUDayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TOUDayTypes");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUHalfHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time");

                    b.Property<int>("HalfHourNr")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TOUHalfHours");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilitySupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilitySupplierId");

                    b.ToTable("TOUHeaders");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUProfileAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("TOUDayTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TOUHalfHourId")
                        .HasColumnType("int");

                    b.Property<int>("TOUHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("TOURegisterId")
                        .HasColumnType("int");

                    b.Property<int>("TOUSeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TOUDayTypeId");

                    b.HasIndex("TOUHalfHourId");

                    b.HasIndex("TOUHeaderId");

                    b.HasIndex("TOURegisterId");

                    b.HasIndex("TOUSeasonId");

                    b.ToTable("TOUProfileAssignments");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOURegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("intName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TOURegisters");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TOUSeasons");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UmfaId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilities");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.UtilitySupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UtilitySuppliers");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.AMRMeter", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.Building", "Building")
                        .WithMany("AMRMeters")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.MeterMakeModel", "MakeModel")
                        .WithMany("AMRMeters")
                        .HasForeignKey("MakeModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.User", "User")
                        .WithMany("AmrMeters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("MakeModel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.AMRScadaUser", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.User", "User")
                        .WithMany("AmrScadaUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.BuildingSupplierUtility", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.Building", "Building")
                        .WithMany("BuildingSupplierUtilities")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.Utility", "Utility")
                        .WithMany("BuildingSupplierUtilities")
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.UtilitySupplier", "UtilitySupplier")
                        .WithMany("BuildingSupplierUtilities")
                        .HasForeignKey("UtilitySupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Utility");

                    b.Navigation("UtilitySupplier");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.MeterMakeModel", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.Utility", "Utility")
                        .WithMany("MeterMakeModels")
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.ScadaRequestDetail", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.AMRMeter", "AmrMeter")
                        .WithMany("ScadaRequestDetails")
                        .HasForeignKey("AmrMeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.AMRScadaUser", "AmrScadaUser")
                        .WithMany("ScadaRequestDetails")
                        .HasForeignKey("AmrScadaUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.ScadaRequestHeader", "Header")
                        .WithMany("ScadaRequestDetails")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmrMeter");

                    b.Navigation("AmrScadaUser");

                    b.Navigation("Header");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TariffHeader", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.TOUHeader", "TOUHeader")
                        .WithMany("TariffHeaders")
                        .HasForeignKey("TOUHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.UtilitySupplier", "UtilitySupplier")
                        .WithMany("TariffHeaders")
                        .HasForeignKey("UtilitySupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TOUHeader");

                    b.Navigation("UtilitySupplier");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUAllocation", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.TOUDaysOfWeek", "TOUDaysOfWeek")
                        .WithMany("TOUAllocations")
                        .HasForeignKey("TOUDaysOfWeekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.TOUHalfHour", "TOUHalfHour")
                        .WithMany("TOUAllocations")
                        .HasForeignKey("TOUHalfHourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.TOURegister", "TOURegister")
                        .WithMany("TOUAllocations")
                        .HasForeignKey("TOURegisterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.TariffHeader", "TariffHeader")
                        .WithMany("TOUAllocations")
                        .HasForeignKey("TariffHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TOUDaysOfWeek");

                    b.Navigation("TOUHalfHour");

                    b.Navigation("TOURegister");

                    b.Navigation("TariffHeader");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUHeader", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.UtilitySupplier", "UtilitySupplier")
                        .WithMany("TOUHeaders")
                        .HasForeignKey("UtilitySupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilitySupplier");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUProfileAssignment", b =>
                {
                    b.HasOne("UMFAPortal.Data.Entities.TOUDayType", "TOUDayType")
                        .WithMany("TOUProfileAssignments")
                        .HasForeignKey("TOUDayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.TOUHalfHour", "TOUHalfHour")
                        .WithMany("TOUProfileAssignments")
                        .HasForeignKey("TOUHalfHourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.TOUHeader", "TOUHeader")
                        .WithMany("TOUProfileAssignments")
                        .HasForeignKey("TOUHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.TOURegister", "TOURegister")
                        .WithMany("TOUProfileAssignments")
                        .HasForeignKey("TOURegisterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UMFAPortal.Data.Entities.TOUSeason", "TOUSeason")
                        .WithMany("TOUProfileAssignments")
                        .HasForeignKey("TOUSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TOUDayType");

                    b.Navigation("TOUHalfHour");

                    b.Navigation("TOUHeader");

                    b.Navigation("TOURegister");

                    b.Navigation("TOUSeason");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.AMRMeter", b =>
                {
                    b.Navigation("ScadaRequestDetails");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.AMRScadaUser", b =>
                {
                    b.Navigation("ScadaRequestDetails");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.Building", b =>
                {
                    b.Navigation("AMRMeters");

                    b.Navigation("BuildingSupplierUtilities");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.MeterMakeModel", b =>
                {
                    b.Navigation("AMRMeters");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.ScadaRequestHeader", b =>
                {
                    b.Navigation("ScadaRequestDetails");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TariffHeader", b =>
                {
                    b.Navigation("TOUAllocations");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUDaysOfWeek", b =>
                {
                    b.Navigation("TOUAllocations");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUDayType", b =>
                {
                    b.Navigation("TOUProfileAssignments");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUHalfHour", b =>
                {
                    b.Navigation("TOUAllocations");

                    b.Navigation("TOUProfileAssignments");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUHeader", b =>
                {
                    b.Navigation("TOUProfileAssignments");

                    b.Navigation("TariffHeaders");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOURegister", b =>
                {
                    b.Navigation("TOUAllocations");

                    b.Navigation("TOUProfileAssignments");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.TOUSeason", b =>
                {
                    b.Navigation("TOUProfileAssignments");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.User", b =>
                {
                    b.Navigation("AmrMeters");

                    b.Navigation("AmrScadaUsers");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.Utility", b =>
                {
                    b.Navigation("BuildingSupplierUtilities");

                    b.Navigation("MeterMakeModels");
                });

            modelBuilder.Entity("UMFAPortal.Data.Entities.UtilitySupplier", b =>
                {
                    b.Navigation("BuildingSupplierUtilities");

                    b.Navigation("TOUHeaders");

                    b.Navigation("TariffHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
